### ISSUE TITLE
Possibly could help with name hashing for Antibirth?

### ISSUE THREAD

**Issue by WhyEssEff** [gibbed/Gibbed.Rebirth#3]
[ran a TrID scan on the _UNKNOWN folder. here's a list of the output files (original name from unpack) and extensions attached to them](https://github.com/gibbed/Gibbed.Rebirth/files/5759550/antibirth.txt)

**Comment by MrSoup678** [comment]
Not  really. Hash is created from relative filepath. We need to find Antibirth's hasher and reverse engineer it.
